spring:
  main:
    web-application-type: none
  http:
    client:
      factory: jdk
      connect-timeout: 45s
      read-timeout: 45s
  security:
    oauth2:
      client:
        registration:
          authserver-client-credentials:
            client-id: jira-ollama-client
            client-secret: ${OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            provider: authserver
            scope: mcp.tools
        provider:
          authserver:
            token-uri: ${JIRA_MCP_SERVER_URL}/oauth2/token
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:3b
    mcp:
      client:
        streamable-http:
          connections:
            jira:
              url: ${JIRA_MCP_SERVER_URL}

logging:
  level:
    root: WARN
